### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by fzhukov** [jamespacileo/django-pure-pagination#40]
Hi! I get this error when install from pip

> $ pip install django-pure-pagination
> Collecting django-pure-pagination
>   Using cached django-pure-pagination-0.3.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-a9onyo91/django-pure-pagination/setup.py", line 5, in <module>
>         README = readme.read()
>       File "/home/django/.pyenv/versions/3.5.2/lib/python3.5/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 672: ordinal not in range(128)
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-a9onyo91/django-pure-pagination/

Can you assist?
Thanks in advance!

**Comment by Burakhan** [comment]
I'm having the same problem

**Comment by wyzewyz** [comment]
I encountered this on a Docker container where for some reason `LANG` was empty.  One workaround is to invoke `pip` with `LANG=en_US.UTF-8` -- i.e.

    LANG=en_US.UTF-8 pip install django-pure-pagination

No source change necessary!

**Comment by elsagong** [comment]
@fzhukov  Hi, I got the same error, could you please tell me how you solve this problem? we are deploying the project, thank you so much for any help. thank you

**Comment by marryjianjian** [comment]
I had the same problem on a Ubuntu16.04 Docker container and I don't know why yet. But I solved the problem by installing from source files with modified setup.py two lines.  

> `with open(os.path.join(os.path.dirname(__file__), 'README.rst'), 'rb') as readme:`

> `long_description=README.decode()`

Hope to be helpful.

**Comment by Annihilater** [comment]
> I had the same problem on a Ubuntu16.04 Docker container and I don't know why yet. But I solved the problem by installing from source files with modified setup.py two lines.
> 
> > `with open(os.path.join(os.path.dirname(__file__), 'README.rst'), 'rb') as readme:`
> 
> > `long_description=README.decode()`
> 
> Hope to be helpful.

Thank you very much! It's worked.

**Comment by scrummie02** [comment]
I have the error now
How is it installed from source

**Comment by ken90242** [comment]
1. `git clone https://github.com/jamespacileo/django-pure-pagination.git`
2. `cd django-pure-pagination`
3. `vim setup.py`
>  Modify setup.py as [what](https://github.com/jamespacileo/django-pure-pagination/issues/40#issuecomment-467761440) @marryjianjian suggested


4. `python setup.py install`
