### ISSUE TITLE
ubuntu14.04 not install

### ISSUE THREAD

**Issue by kuangshp** [jamespacileo/django-pure-pagination#53]
ubuntu14.04 error 0855970a5ce02ea12f5a53d520315f200b4847a1/django-pure-pagination-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-isuua6j4/django-pure-pagination/setup.py", line 5, in <module>
        README = readme.read()
      File "/var/env/django_env/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 672: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-isuua6j4/django-pure-pagination/
(django_env) root@iZ941w016mwZ:~#

**Comment by antoniocdff** [comment]
me too, in python2.7 works

**Comment by AnderUstarroz** [comment]
I think this was fixed on the following [pull request](https://github.com/jamespacileo/django-pure-pagination/pull/62) for Python 3. We just need it to be merged and release a new version.
