### ISSUE TITLE
error installing on ubuntu 18.04

### ISSUE THREAD

**Issue by scrummie02** [jamespacileo/django-pure-pagination#61]
```
 Downloading django-pure-pagination-0.3.0.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/mayan-edms/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zh_8icc8/django-pure-pagination/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zh_8icc8/django-pure-pagination/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-zh_8icc8/django-pure-pagination/pip-egg-info
         cwd: /tmp/pip-install-zh_8icc8/django-pure-pagination/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zh_8icc8/django-pure-pagination/setup.py", line 5, in <module>
        README = readme.read()
      File "/opt/mayan-edms/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 672: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
This is from PIP install on the latest version of PIP

**Comment by AnderUstarroz** [comment]
I think this was fixed by @ekinertac on the following [pull request](https://github.com/jamespacileo/django-pure-pagination/pull/62). We just need @jamespacileo to merge it and release a new version.
